export const NETWORK_WARNING_SHOW = 'NETWORK_WARNING_SHOW'
export const APPSTATUS_GET_START = 'APPSTATUS_GET_START'
export const APPSTATUS_GET_DONE = 'APPSTATUS_GET_DONE'

export const INSTALL_GET_START = 'INSTALL_GET_START'
export const INSTALL_GET_DONE = 'INSTALL_GET_DONE'

export const UPDATE_POST_START = 'UPDATE_POST_START'
export const UPDATE_POST_DONE = 'UPDATE_POST_DONE'

export const RCSITEKEY_CHANGE = 'RCSITEKEY_CHANGE'
export const RCSITESECRET_CHANGE = 'RCSITESECRET_CHANGE'

export const ERROR_DISMISS = 'ERROR_DISMISS'
export const SUCCESS_DISMISS = 'SUCCESS_DISMISS'
