export const NETWORK_WARNING_SHOW = 'NETWORK_WARNING_SHOW'
export const APPSTATUS_GET_START = 'APPSTATUS_GET_START'
export const APPSTATUS_GET_DONE = 'APPSTATUS_GET_DONE'

export const INSTALL_GET_START = 'INSTALL_GET_START'
export const INSTALL_GET_DONE = 'INSTALL_GET_DONE'

export const RCSITEKEY_CHANGE = 'RCSITEKEY_CHANGE'
